### ISSUE TITLE
Fail with Morepath 0.15 and multiple attempts

### ISSUE THREAD

**Issue by href** [morepath/more.transaction#5]
Using multiple attempts (> 1) and Morepath 0.15 (unreleased) results in lots of 404s because the paths cannot be resolved correctly anymore.

This is du to the change of the unconsumed path order with Morepath 0.15:
https://github.com/morepath/morepath/commit/e2c7c4224ab68b65acd728446795646d5c822a36

This conflicts with https://github.com/morepath/more.transaction/blob/fe275f0/more/transaction/main.py#L64

Ideally we make sure that there's some kind of public api for this in morepath, so we don't have to keep those implementations in lockstep.

**Comment by faassen** [comment]
Ah, yes, using an internal isn't really right, and I think I am to blame.

**Comment by faassen** [comment]
Here are some interactions that should possibly be internal:

* ``request.make_body_seekable`` from webob, so public enough, but should possibly be abstracted away.

* ``request.unconsumed`` this is set. It's published in the morepath API but is it meant to be settable?

* ``morepath.traject.parse_path`` is an internal function.

* ``request.path_info``; part of webob and used to access and manipulate ``PATH_INFO`` in the environment, but perhaps should be abstracted away.

* ``request.path``; part of webob too; the path without host or query string. This is used to store things on the transaction.

**Comment by faassen** [comment]
This got fixed. We have a ``request.reset`` in Morepath now. It also fixes a new bug I uncovered where the current app wasn't properly reset.
