### ISSUE TITLE
userid not taken properly

### ISSUE THREAD

**Issue by faassen** [morepath/more.transaction#6]
The code has some XXX marked that it should get the userid somehow from the identity on the request. Currently this is not happening, so the info is not properly recorded in the transaction.

**Comment by taschini** [comment]
That should be replaced by

```python
userid = request.identity
```

and the test a little further down ``if userid:`` with 

```python
if userid is not morepath.NO_IDENTITY:
    ...
```

**Comment by faassen** [comment]
`request.identity`` can be an arbitrary object, I don't think that would work. I know the ZODB can store userid information, but I think only as a string.

**Comment by taschini** [comment]
Do we want to stipulate that ``morepath.Identity`` objects can be uniquely converted to string?
That would require a change to the Morepath API.

**Comment by faassen** [comment]
No, I don't think we can require this. I think we need an API on ``morepath.Identity`` to get a userid that identifies it. It looks like we in fact already have it, as there's a ``userid`` attribute on the base identity class and ``NoIdentity`` as well (where it is ``None``). But we do need to expose that in the Morepath docs; I'll create an issue.
