### ISSUE TITLE
reraise is complicated

### ISSUE THREAD

**Issue by faassen** [morepath/more.transaction#7]
There's complicated logic to implement a ``reraise`` functionality, different in Python 2 and 3. I am wondering why this is not simply implemented with ``raise`` (without arguments). Perhaps this has to do with some kind of traceback manipulation I don't quite understand.

Note also that the PY3 compat layer defines an ``exec_`` function that doesn't appear to be used.

If we can get rid of the complexity that would be nice -- running exec and frame manipulation is pretty extreme.

**Comment by faassen** [comment]
To figure out why it is this way we should investigate the pyramid_tm logic.

**Comment by taschini** [comment]
That had caught my eye too. AFAICS there is no reason why a naked ``raise`` shouldn't be enough.

**Comment by taschini** [comment]
Here's the relevant commit: https://github.com/Pylons/pyramid_tm/commit/1c4c389242ddcc145c89a32e97445f26a9db1481

They went from a context manager, which requires ``reraise`` as part of the ``__exit__`` special method, to a ``try…except`` clause, and simply copied over the code fragment.

I'm definitely of the opinion that ``reraise`` can be safely removed, ``compat.py`` deleted and the except clause simplified to:

```python
            except:
                ex_type, ex_value = sys.exc_info()[:2]
                retryable = manager._retryable(ex_type, ex_value)
                manager.abort()
                if (number <= 0) or (not retryable):
                    raise
```

**Comment by faassen** [comment]
@taschini thanks for looking into it! Go ahead and apply this simplication.
