### ISSUE TITLE
Raises unicode error with transaction 2.0

### ISSUE THREAD

**Issue by henri-hulski** [morepath/more.transaction#8]
When more.transaction is used with transaction 2.0 the following type error appears:
```sh
env/local/lib/python2.7/site-packages/more/transaction/main.py:64: in transaction_tween
    t.note(request.path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <transaction._transaction.Transaction object at 0x7f1651c780d0>, text = '/'

    def note(self, text):
        """ See ITransaction.
            """

        if not isinstance(text, text_type):
>           raise TypeError("Note must be text (unicode)")
E           TypeError: Note must be text (unicode)

env/local/lib/python2.7/site-packages/transaction/_transaction.py:537: TypeError
```
This happens because in [Transaction 2.0.3](https://github.com/zopefoundation/transaction/blob/master/CHANGES.rst#203-2016-11-17) 
> The user and description fields must now be set with text (unicode) data. Previously, if bytes were provided, they’d be decoded as ASCII.

**Comment by hlopezvg** [comment]
@henri-hulski same here, do you know a workaround?
Thanks

**Comment by henri-hulski** [comment]
@hlopezvg for now just use transaction pre 2.0.

**Comment by hlopezvg** [comment]
@henri-hulski Thanks, is working now.

**Comment by href** [comment]
Fixed with https://github.com/morepath/more.transaction/commit/97ba66942df49f7ae0facff6ad153232959eb9a9. The new [0.8 release on PyPI](https://pypi.python.org/pypi/more.transaction/0.8) includes this fix.
